# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ba82b1504b4a097fde5cddb96aecfd7dea9a5892169ce81040d00a0699f473ecf5967bdcd0c7c260dcc502c0c68aeb80296190464167e77308b7b6cfa4911fb

test:
  secret_key_base: cbb3e30eac52bee326f20a033622fad7478e549520c9ab116f0fa330986409d4fd5be343b0000f7d24458536678e8198f1094a44aea79ccceb69a8b028c82827

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
